# Generated by Django 5.0.2 on 2024-02-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
