# Generated by Django 5.0.2 on 2024-02-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_appuser_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
