# Generated by Django 5.0.2 on 2024-02-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_appuser_firstname_appuser_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
