# Generated by Django 5.0.3 on 2024-03-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_appuser_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('model_year', models.PositiveIntegerField()),
                ('daily_rate', models.IntegerField()),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('image_file', models.ImageField(upload_to='car_images/')),
            ],
        ),
    ]
